language: node_js
node_js:
  - "7"
  - "8"
  - "9"
env:
  global:
    # Necessary to build Node.js 0.6 on Travis CI images
    - "CC=gcc-4.6 CXX=g++-4.6"

dist: trusty
addons:
  apt:
    packages:
      - g++-4.6
sudo: required
services:
  - mysql

install:
  - "npm install"

script:
  - "npm run build:min"
  - "npm test"
 # - "test   -z $(npm -ps ls nyc) || npm run-script test-ci"
 # - "test   -z $(npm -ps ls eslint) || npm run-script lint"

after_script:
#  - "test -d .nyc_output && npm install coveralls@2 && nyc report --reporter=text-lcov | coveralls"
  - "test -d ./coverage/lcov.info && npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"